KANA_DATA = [
    # === 清音 (Seion) - Basic ===
    {"hiragana": "あ", "katakana": "ア", "romaji": "a", "type": "seion", "row": "a"},
    {"hiragana": "い", "katakana": "イ", "romaji": "i", "type": "seion", "row": "a"},
    {"hiragana": "う", "katakana": "ウ", "romaji": "u", "type": "seion", "row": "a"},
    {"hiragana": "え", "katakana": "エ", "romaji": "e", "type": "seion", "row": "a"},
    {"hiragana": "お", "katakana": "オ", "romaji": "o", "type": "seion", "row": "a"},

    {"hiragana": "か", "katakana": "カ", "romaji": "ka", "type": "seion", "row": "ka"},
    {"hiragana": "き", "katakana": "キ", "romaji": "ki", "type": "seion", "row": "ka"},
    {"hiragana": "く", "katakana": "ク", "romaji": "ku", "type": "seion", "row": "ka"},
    {"hiragana": "け", "katakana": "ケ", "romaji": "ke", "type": "seion", "row": "ka"},
    {"hiragana": "こ", "katakana": "コ", "romaji": "ko", "type": "seion", "row": "ka"},

    {"hiragana": "さ", "katakana": "サ", "romaji": "sa", "type": "seion", "row": "sa"},
    {"hiragana": "し", "katakana": "シ", "romaji": "shi", "type": "seion", "row": "sa"},
    {"hiragana": "す", "katakana": "ス", "romaji": "su", "type": "seion", "row": "sa"},
    {"hiragana": "せ", "katakana": "セ", "romaji": "se", "type": "seion", "row": "sa"},
    {"hiragana": "そ", "katakana": "ソ", "romaji": "so", "type": "seion", "row": "sa"},

    {"hiragana": "た", "katakana": "タ", "romaji": "ta", "type": "seion", "row": "ta"},
    {"hiragana": "ち", "katakana": "チ", "romaji": "chi", "type": "seion", "row": "ta"},
    {"hiragana": "つ", "katakana": "ツ", "romaji": "tsu", "type": "seion", "row": "ta"},
    {"hiragana": "て", "katakana": "テ", "romaji": "te", "type": "seion", "row": "ta"},
    {"hiragana": "と", "katakana": "ト", "romaji": "to", "type": "seion", "row": "ta"},

    {"hiragana": "な", "katakana": "ナ", "romaji": "na", "type": "seion", "row": "na"},
    {"hiragana": "に", "katakana": "ニ", "romaji": "ni", "type": "seion", "row": "na"},
    {"hiragana": "ぬ", "katakana": "ヌ", "romaji": "nu", "type": "seion", "row": "na"},
    {"hiragana": "ね", "katakana": "ネ", "romaji": "ne", "type": "seion", "row": "na"},
    {"hiragana": "の", "katakana": "ノ", "romaji": "no", "type": "seion", "row": "na"},

    {"hiragana": "は", "katakana": "ハ", "romaji": "ha", "type": "seion", "row": "ha"},
    {"hiragana": "ひ", "katakana": "ヒ", "romaji": "hi", "type": "seion", "row": "ha"},
    {"hiragana": "ふ", "katakana": "フ", "romaji": "fu", "type": "seion", "row": "ha"},
    {"hiragana": "へ", "katakana": "ヘ", "romaji": "he", "type": "seion", "row": "ha"},
    {"hiragana": "ほ", "katakana": "ホ", "romaji": "ho", "type": "seion", "row": "ha"},

    {"hiragana": "ま", "katakana": "マ", "romaji": "ma", "type": "seion", "row": "ma"},
    {"hiragana": "み", "katakana": "ミ", "romaji": "mi", "type": "seion", "row": "ma"},
    {"hiragana": "む", "katakana": "ム", "romaji": "mu", "type": "seion", "row": "ma"},
    {"hiragana": "め", "katakana": "メ", "romaji": "me", "type": "seion", "row": "ma"},
    {"hiragana": "も", "katakana": "モ", "romaji": "mo", "type": "seion", "row": "ma"},

    {"hiragana": "や", "katakana": "ヤ", "romaji": "ya", "type": "seion", "row": "ya"},
    {"hiragana": "ゆ", "katakana": "ユ", "romaji": "yu", "type": "seion", "row": "ya"},
    {"hiragana": "よ", "katakana": "ヨ", "romaji": "yo", "type": "seion", "row": "ya"},

    {"hiragana": "ら", "katakana": "ラ", "romaji": "ra", "type": "seion", "row": "ra"},
    {"hiragana": "り", "katakana": "リ", "romaji": "ri", "type": "seion", "row": "ra"},
    {"hiragana": "る", "katakana": "ル", "romaji": "ru", "type": "seion", "row": "ra"},
    {"hiragana": "れ", "katakana": "レ", "romaji": "re", "type": "seion", "row": "ra"},
    {"hiragana": "ろ", "katakana": "ロ", "romaji": "ro", "type": "seion", "row": "ra"},

    {"hiragana": "わ", "katakana": "ワ", "romaji": "wa", "type": "seion", "row": "wa"},
    {"hiragana": "を", "katakana": "ヲ", "romaji": "wo", "type": "seion", "row": "wa"},
    {"hiragana": "ん", "katakana": "ン", "romaji": "n", "type": "seion", "row": "wa"},

    # === 浊音 (Dakuon) ===
    {"hiragana": "が", "katakana": "ガ", "romaji": "ga", "type": "dakuon", "row": "ga"},
    {"hiragana": "ぎ", "katakana": "ギ", "romaji": "gi", "type": "dakuon", "row": "ga"},
    {"hiragana": "ぐ", "katakana": "グ", "romaji": "gu", "type": "dakuon", "row": "ga"},
    {"hiragana": "げ", "katakana": "ゲ", "romaji": "ge", "type": "dakuon", "row": "ga"},
    {"hiragana": "ご", "katakana": "ゴ", "romaji": "go", "type": "dakuon", "row": "ga"},

    {"hiragana": "ざ", "katakana": "ザ", "romaji": "za", "type": "dakuon", "row": "za"},
    {"hiragana": "じ", "katakana": "ジ", "romaji": "ji", "type": "dakuon", "row": "za"},
    {"hiragana": "ず", "katakana": "ズ", "romaji": "zu", "type": "dakuon", "row": "za"},
    {"hiragana": "ぜ", "katakana": "ゼ", "romaji": "ze", "type": "dakuon", "row": "za"},
    {"hiragana": "ぞ", "katakana": "ゾ", "romaji": "zo", "type": "dakuon", "row": "za"},

    {"hiragana": "だ", "katakana": "ダ", "romaji": "da", "type": "dakuon", "row": "da"},
    {"hiragana": "ぢ", "katakana": "ヂ", "romaji": "di", "type": "dakuon", "row": "da"},
    {"hiragana": "づ", "katakana": "ヅ", "romaji": "du", "type": "dakuon", "row": "da"},
    {"hiragana": "で", "katakana": "デ", "romaji": "de", "type": "dakuon", "row": "da"},
    {"hiragana": "ど", "katakana": "ド", "romaji": "do", "type": "dakuon", "row": "da"},

    {"hiragana": "ば", "katakana": "バ", "romaji": "ba", "type": "dakuon", "row": "ba"},
    {"hiragana": "び", "katakana": "ビ", "romaji": "bi", "type": "dakuon", "row": "ba"},
    {"hiragana": "ぶ", "katakana": "ブ", "romaji": "bu", "type": "dakuon", "row": "ba"},
    {"hiragana": "べ", "katakana": "ベ", "romaji": "be", "type": "dakuon", "row": "ba"},
    {"hiragana": "ぼ", "katakana": "ボ", "romaji": "bo", "type": "dakuon", "row": "ba"},

    # === 半浊音 (Handakuon) ===
    {"hiragana": "ぱ", "katakana": "パ", "romaji": "pa", "type": "handakuon", "row": "pa"},
    {"hiragana": "ぴ", "katakana": "ピ", "romaji": "pi", "type": "handakuon", "row": "pa"},
    {"hiragana": "ぷ", "katakana": "プ", "romaji": "pu", "type": "handakuon", "row": "pa"},
    {"hiragana": "ぺ", "katakana": "ペ", "romaji": "pe", "type": "handakuon", "row": "pa"},
    {"hiragana": "ぽ", "katakana": "ポ", "romaji": "po", "type": "handakuon", "row": "pa"},

    # === 拗音 (Youon) ===
    {"hiragana": "きゃ", "katakana": "キャ", "romaji": "kya", "type": "youon", "row": "kya"},
    {"hiragana": "きゅ", "katakana": "キュ", "romaji": "kyu", "type": "youon", "row": "kya"},
    {"hiragana": "きょ", "katakana": "キョ", "romaji": "kyo", "type": "youon", "row": "kya"},

    {"hiragana": "しゃ", "katakana": "シャ", "romaji": "sha", "type": "youon", "row": "sha"},
    {"hiragana": "しゅ", "katakana": "シュ", "romaji": "shu", "type": "youon", "row": "sha"},
    {"hiragana": "しょ", "katakana": "ショ", "romaji": "sho", "type": "youon", "row": "sha"},

    {"hiragana": "ちゃ", "katakana": "チャ", "romaji": "cha", "type": "youon", "row": "cha"},
    {"hiragana": "ちゅ", "katakana": "チュ", "romaji": "chu", "type": "youon", "row": "cha"},
    {"hiragana": "ちょ", "katakana": "チョ", "romaji": "cho", "type": "youon", "row": "cha"},

    {"hiragana": "にゃ", "katakana": "ニャ", "romaji": "nya", "type": "youon", "row": "nya"},
    {"hiragana": "にゅ", "katakana": "ニュ", "romaji": "nyu", "type": "youon", "row": "nya"},
    {"hiragana": "にょ", "katakana": "ニョ", "romaji": "nyo", "type": "youon", "row": "nya"},

    {"hiragana": "ひゃ", "katakana": "ヒャ", "romaji": "hya", "type": "youon", "row": "hya"},
    {"hiragana": "ひゅ", "katakana": "ヒュ", "romaji": "hyu", "type": "youon", "row": "hya"},
    {"hiragana": "ひょ", "katakana": "ヒョ", "romaji": "hyo", "type": "youon", "row": "hya"},

    {"hiragana": "みゃ", "katakana": "ミャ", "romaji": "mya", "type": "youon", "row": "mya"},
    {"hiragana": "みゅ", "katakana": "ミュ", "romaji": "myu", "type": "youon", "row": "mya"},
    {"hiragana": "みょ", "katakana": "ミョ", "romaji": "myo", "type": "youon", "row": "mya"},

    {"hiragana": "りゃ", "katakana": "リャ", "romaji": "rya", "type": "youon", "row": "rya"},
    {"hiragana": "りゅ", "katakana": "リュ", "romaji": "ryu", "type": "youon", "row": "rya"},
    {"hiragana": "りょ", "katakana": "リョ", "romaji": "ryo", "type": "youon", "row": "rya"},

    {"hiragana": "ぎゃ", "katakana": "ギャ", "romaji": "gya", "type": "youon", "row": "gya"},
    {"hiragana": "ぎゅ", "katakana": "ギュ", "romaji": "gyu", "type": "youon", "row": "gya"},
    {"hiragana": "ぎょ", "katakana": "ギョ", "romaji": "gyo", "type": "youon", "row": "gya"},

    {"hiragana": "じゃ", "katakana": "ジャ", "romaji": "ja", "type": "youon", "row": "ja"},
    {"hiragana": "じゅ", "katakana": "ジュ", "romaji": "ju", "type": "youon", "row": "ja"},
    {"hiragana": "じょ", "katakana": "ジョ", "romaji": "jo", "type": "youon", "row": "ja"},

    {"hiragana": "びゃ", "katakana": "ビャ", "romaji": "bya", "type": "youon", "row": "bya"},
    {"hiragana": "びゅ", "katakana": "ビュ", "romaji": "byu", "type": "youon", "row": "bya"},
    {"hiragana": "びょ", "katakana": "ビョ", "romaji": "byo", "type": "youon", "row": "bya"},

    {"hiragana": "ぴゃ", "katakana": "ピャ", "romaji": "pya", "type": "youon", "row": "pya"},
    {"hiragana": "ぴゅ", "katakana": "ピュ", "romaji": "pyu", "type": "youon", "row": "pya"},
    {"hiragana": "ぴょ", "katakana": "ピョ", "romaji": "pyo", "type": "youon", "row": "pya"},
]

VOCABULARY = {
    "a": [{"word": "あめ", "romaji": "ame", "kanji": "雨", "meaning": "雨，下雨"},
          {"word": "あさ", "romaji": "asa", "kanji": "朝", "meaning": "早上"}],
    "i": [{"word": "いぬ", "romaji": "inu", "kanji": "犬", "meaning": "狗"},
          {"word": "いえ", "romaji": "ie", "kanji": "家", "meaning": "家"}],
    "u": [{"word": "うみ", "romaji": "umi", "kanji": "海", "meaning": "大海"},
          {"word": "うた", "romaji": "uta", "kanji": "歌", "meaning": "歌曲"}],
    "e": [{"word": "えき", "romaji": "eki", "kanji": "駅", "meaning": "车站"},
          {"word": "えん", "romaji": "en", "kanji": "円", "meaning": "日元"}],
    "o": [{"word": "おちゃ", "romaji": "ocha", "kanji": "お茶", "meaning": "茶"},
          {"word": "おかね", "romaji": "okane", "kanji": "お金", "meaning": "钱"}],
    "ka": [{"word": "かさ", "romaji": "kasa", "kanji": "傘", "meaning": "伞"},
           {"word": "かわ", "romaji": "kawa", "kanji": "川", "meaning": "河"}],
    "ki": [{"word": "きもの", "romaji": "kimono", "kanji": "着物", "meaning": "和服"},
           {"word": "きって", "romaji": "kitte", "kanji": "切手", "meaning": "邮票"}],
    "ku": [{"word": "くるま", "romaji": "kuruma", "kanji": "車", "meaning": "汽车"},
           {"word": "くつ", "romaji": "kutsu", "kanji": "靴", "meaning": "鞋子"}],
    "ke": [{"word": "けしゴム", "romaji": "keshigomu", "kanji": "消しゴム", "meaning": "橡皮擦"},
           {"word": "けさ", "romaji": "kesa", "kanji": "今朝", "meaning": "今天早上"}],
    "ko": [{"word": "こども", "romaji": "kodomo", "kanji": "子供", "meaning": "孩子"},
           {"word": "ここ", "romaji": "koko", "kanji": "", "meaning": "这里"}],
    "sa": [{"word": "さくら", "romaji": "sakura", "kanji": "桜", "meaning": "樱花"},
           {"word": "さかな", "romaji": "sakana", "kanji": "魚", "meaning": "鱼"}],
    "shi": [{"word": "しんぶん", "romaji": "shinbun", "kanji": "新聞", "meaning": "报纸"},
            {"word": "しろ", "romaji": "shiro", "kanji": "白", "meaning": "白色"}],
    "su": [{"word": "すし", "romaji": "sushi", "kanji": "寿司", "meaning": "寿司"},
           {"word": "すき", "romaji": "suki", "kanji": "好き", "meaning": "喜欢"}],
    "se": [{"word": "せんせい", "romaji": "sensei", "kanji": "先生", "meaning": "老师"},
           {"word": "せかい", "romaji": "sekai", "kanji": "世界", "meaning": "世界"}],
    "so": [{"word": "そら", "romaji": "sora", "kanji": "空", "meaning": "天空"},
           {"word": "そと", "romaji": "soto", "kanji": "外", "meaning": "外面"}],
    "ta": [{"word": "たまご", "romaji": "tamago", "kanji": "卵", "meaning": "鸡蛋"},
           {"word": "たべもの", "romaji": "tabemono", "kanji": "食べ物", "meaning": "食物"}],
    "chi": [{"word": "ちず", "romaji": "chizu", "kanji": "地図", "meaning": "地图"},
            {"word": "ちいさい", "romaji": "chiisai", "kanji": "小さい", "meaning": "小的"}],
    "tsu": [{"word": "つき", "romaji": "tsuki", "kanji": "月", "meaning": "月亮"},
            {"word": "つくえ", "romaji": "tsukue", "kanji": "机", "meaning": "桌子"}],
    "te": [{"word": "てがみ", "romaji": "tegami", "kanji": "手紙", "meaning": "信"},
           {"word": "てんき", "romaji": "tenki", "kanji": "天気", "meaning": "天气"}],
    "to": [{"word": "ともだち", "romaji": "tomodachi", "kanji": "友達", "meaning": "朋友"},
           {"word": "とけい", "romaji": "tokei", "kanji": "時計", "meaning": "钟表"}],
    "na": [{"word": "なつ", "romaji": "natsu", "kanji": "夏", "meaning": "夏天"},
           {"word": "なまえ", "romaji": "namae", "kanji": "名前", "meaning": "名字"}],
    "ni": [{"word": "にほん", "romaji": "nihon", "kanji": "日本", "meaning": "日本"},
           {"word": "にく", "romaji": "niku", "kanji": "肉", "meaning": "肉"}],
    "nu": [{"word": "ぬいぐるみ", "romaji": "nuigurumi", "kanji": "", "meaning": "毛绒玩具"},
           {"word": "ぬの", "romaji": "nuno", "kanji": "布", "meaning": "布"}],
    "ne": [{"word": "ねこ", "romaji": "neko", "kanji": "猫", "meaning": "猫"},
           {"word": "ねる", "romaji": "neru", "kanji": "寝る", "meaning": "睡觉"}],
    "no": [{"word": "のみもの", "romaji": "nomimono", "kanji": "飲み物", "meaning": "饮料"},
           {"word": "のり", "romaji": "nori", "kanji": "海苔", "meaning": "海苔"}],
    "ha": [{"word": "はな", "romaji": "hana", "kanji": "花", "meaning": "花"},
           {"word": "はし", "romaji": "hashi", "kanji": "箸", "meaning": "筷子"}],
    "hi": [{"word": "ひと", "romaji": "hito", "kanji": "人", "meaning": "人"},
           {"word": "ひこうき", "romaji": "hikouki", "kanji": "飛行機", "meaning": "飞机"}],
    "fu": [{"word": "ふゆ", "romaji": "fuyu", "kanji": "冬", "meaning": "冬天"},
           {"word": "ふね", "romaji": "fune", "kanji": "船", "meaning": "船"}],
    "he": [{"word": "へや", "romaji": "heya", "kanji": "部屋", "meaning": "房间"},
           {"word": "へいわ", "romaji": "heiwa", "kanji": "平和", "meaning": "和平"}],
    "ho": [{"word": "ほん", "romaji": "hon", "kanji": "本", "meaning": "书"},
           {"word": "ほし", "romaji": "hoshi", "kanji": "星", "meaning": "星星"}],
    "ma": [{"word": "まど", "romaji": "mado", "kanji": "窓", "meaning": "窗户"},
           {"word": "まち", "romaji": "machi", "kanji": "町", "meaning": "城镇"}],
    "mi": [{"word": "みず", "romaji": "mizu", "kanji": "水", "meaning": "水"},
           {"word": "みち", "romaji": "michi", "kanji": "道", "meaning": "道路"}],
    "mu": [{"word": "むし", "romaji": "mushi", "kanji": "虫", "meaning": "虫子"},
           {"word": "むすめ", "romaji": "musume", "kanji": "娘", "meaning": "女儿"}],
    "me": [{"word": "めがね", "romaji": "megane", "kanji": "眼鏡", "meaning": "眼镜"},
           {"word": "め", "romaji": "me", "kanji": "目", "meaning": "眼睛"}],
    "mo": [{"word": "もり", "romaji": "mori", "kanji": "森", "meaning": "森林"},
           {"word": "もの", "romaji": "mono", "kanji": "物", "meaning": "东西"}],
    "ya": [{"word": "やま", "romaji": "yama", "kanji": "山", "meaning": "山"},
           {"word": "やすみ", "romaji": "yasumi", "kanji": "休み", "meaning": "休息"}],
    "yu": [{"word": "ゆき", "romaji": "yuki", "kanji": "雪", "meaning": "雪"},
           {"word": "ゆめ", "romaji": "yume", "kanji": "夢", "meaning": "梦"}],
    "yo": [{"word": "よる", "romaji": "yoru", "kanji": "夜", "meaning": "夜晚"},
           {"word": "よむ", "romaji": "yomu", "kanji": "読む", "meaning": "阅读"}],
    "ra": [{"word": "らいねん", "romaji": "rainen", "kanji": "来年", "meaning": "明年"},
           {"word": "ラーメン", "romaji": "raamen", "kanji": "", "meaning": "拉面"}],
    "ri": [{"word": "りんご", "romaji": "ringo", "kanji": "", "meaning": "苹果"},
           {"word": "りょうり", "romaji": "ryouri", "kanji": "料理", "meaning": "料理"}],
    "ru": [{"word": "るす", "romaji": "rusu", "kanji": "留守", "meaning": "不在家"},
           {"word": "ルール", "romaji": "ruuru", "kanji": "", "meaning": "规则"}],
    "re": [{"word": "れいぞうこ", "romaji": "reizouko", "kanji": "冷蔵庫", "meaning": "冰箱"},
           {"word": "れきし", "romaji": "rekishi", "kanji": "歴史", "meaning": "历史"}],
    "ro": [{"word": "ろうか", "romaji": "rouka", "kanji": "廊下", "meaning": "走廊"},
           {"word": "ろく", "romaji": "roku", "kanji": "六", "meaning": "六"}],
    "wa": [{"word": "わたし", "romaji": "watashi", "kanji": "私", "meaning": "我"},
           {"word": "わかる", "romaji": "wakaru", "kanji": "分かる", "meaning": "明白"}],
    "wo": [{"word": "ごはんをたべる", "romaji": "gohan wo taberu", "kanji": "ご飯を食べる", "meaning": "吃饭"}],
    "n": [{"word": "にほん", "romaji": "nihon", "kanji": "日本", "meaning": "日本"},
          {"word": "みかん", "romaji": "mikan", "kanji": "", "meaning": "橘子"}],
    "ga": [{"word": "がっこう", "romaji": "gakkou", "kanji": "学校", "meaning": "学校"},
           {"word": "がいこく", "romaji": "gaikoku", "kanji": "外国", "meaning": "外国"}],
    "gi": [{"word": "ぎんこう", "romaji": "ginkou", "kanji": "銀行", "meaning": "银行"},
           {"word": "ぎゅうにゅう", "romaji": "gyuunyuu", "kanji": "牛乳", "meaning": "牛奶"}],
    "gu": [{"word": "ぐんて", "romaji": "gunte", "kanji": "軍手", "meaning": "手套"},
           {"word": "ぐあい", "romaji": "guai", "kanji": "具合", "meaning": "状况"}],
    "ge": [{"word": "げんき", "romaji": "genki", "kanji": "元気", "meaning": "精神，健康"},
           {"word": "げつようび", "romaji": "getsuyoubi", "kanji": "月曜日", "meaning": "星期一"}],
    "go": [{"word": "ごはん", "romaji": "gohan", "kanji": "ご飯", "meaning": "米饭"},
           {"word": "ごご", "romaji": "gogo", "kanji": "午後", "meaning": "下午"}],
    "za": [{"word": "ざっし", "romaji": "zasshi", "kanji": "雑誌", "meaning": "杂志"},
           {"word": "ざいりょう", "romaji": "zairyou", "kanji": "材料", "meaning": "材料"}],
    "ji": [{"word": "じかん", "romaji": "jikan", "kanji": "時間", "meaning": "时间"},
           {"word": "じしょ", "romaji": "jisho", "kanji": "辞書", "meaning": "词典"}],
    "zu": [{"word": "ずっと", "romaji": "zutto", "kanji": "", "meaning": "一直"},
           {"word": "ずかん", "romaji": "zukan", "kanji": "図鑑", "meaning": "图鉴"}],
    "ze": [{"word": "ぜんぶ", "romaji": "zenbu", "kanji": "全部", "meaning": "全部"},
           {"word": "ぜったい", "romaji": "zettai", "kanji": "絶対", "meaning": "绝对"}],
    "zo": [{"word": "ぞう", "romaji": "zou", "kanji": "象", "meaning": "大象"},
           {"word": "ぞうきん", "romaji": "zoukin", "kanji": "雑巾", "meaning": "抹布"}],
    "da": [{"word": "だいがく", "romaji": "daigaku", "kanji": "大学", "meaning": "大学"},
           {"word": "だれ", "romaji": "dare", "kanji": "誰", "meaning": "谁"}],
    "di": [{"word": "ちぢむ", "romaji": "chijimu", "kanji": "縮む", "meaning": "缩小"}],
    "du": [{"word": "つづく", "romaji": "tsuzuku", "kanji": "続く", "meaning": "继续"}],
    "de": [{"word": "でんわ", "romaji": "denwa", "kanji": "電話", "meaning": "电话"},
           {"word": "でぐち", "romaji": "deguchi", "kanji": "出口", "meaning": "出口"}],
    "do": [{"word": "どうぶつ", "romaji": "doubutsu", "kanji": "動物", "meaning": "动物"},
           {"word": "どようび", "romaji": "doyoubi", "kanji": "土曜日", "meaning": "星期六"}],
    "ba": [{"word": "ばんごはん", "romaji": "bangohan", "kanji": "晩ご飯", "meaning": "晚饭"},
           {"word": "ばしょ", "romaji": "basho", "kanji": "場所", "meaning": "地方"}],
    "bi": [{"word": "びじゅつかん", "romaji": "bijutsukan", "kanji": "美術館", "meaning": "美术馆"},
           {"word": "びょういん", "romaji": "byouin", "kanji": "病院", "meaning": "医院"}],
    "bu": [{"word": "ぶんか", "romaji": "bunka", "kanji": "文化", "meaning": "文化"},
           {"word": "ぶた", "romaji": "buta", "kanji": "豚", "meaning": "猪"}],
    "be": [{"word": "べんきょう", "romaji": "benkyou", "kanji": "勉強", "meaning": "学习"},
           {"word": "べんり", "romaji": "benri", "kanji": "便利", "meaning": "方便"}],
    "bo": [{"word": "ぼうし", "romaji": "boushi", "kanji": "帽子", "meaning": "帽子"},
           {"word": "ぼく", "romaji": "boku", "kanji": "僕", "meaning": "我（男性）"}],
    "pa": [{"word": "パン", "romaji": "pan", "kanji": "", "meaning": "面包"},
           {"word": "パーティー", "romaji": "paatii", "kanji": "", "meaning": "派对"}],
    "pi": [{"word": "ピアノ", "romaji": "piano", "kanji": "", "meaning": "钢琴"},
           {"word": "ピンク", "romaji": "pinku", "kanji": "", "meaning": "粉色"}],
    "pu": [{"word": "プール", "romaji": "puuru", "kanji": "", "meaning": "游泳池"},
           {"word": "プレゼント", "romaji": "purezento", "kanji": "", "meaning": "礼物"}],
    "pe": [{"word": "ペン", "romaji": "pen", "kanji": "", "meaning": "笔"},
           {"word": "ページ", "romaji": "peeji", "kanji": "", "meaning": "页"}],
    "po": [{"word": "ポケット", "romaji": "poketto", "kanji": "", "meaning": "口袋"},
           {"word": "ポスト", "romaji": "posuto", "kanji": "", "meaning": "邮筒"}],
    "kya": [{"word": "きゃく", "romaji": "kyaku", "kanji": "客", "meaning": "客人"}],
    "kyu": [{"word": "きゅうり", "romaji": "kyuuri", "kanji": "", "meaning": "黄瓜"}],
    "kyo": [{"word": "きょう", "romaji": "kyou", "kanji": "今日", "meaning": "今天"},
            {"word": "きょうしつ", "romaji": "kyoushitsu", "kanji": "教室", "meaning": "教室"}],
    "sha": [{"word": "しゃしん", "romaji": "shashin", "kanji": "写真", "meaning": "照片"},
            {"word": "しゃかい", "romaji": "shakai", "kanji": "社会", "meaning": "社会"}],
    "shu": [{"word": "しゅくだい", "romaji": "shukudai", "kanji": "宿題", "meaning": "作业"},
            {"word": "しゅみ", "romaji": "shumi", "kanji": "趣味", "meaning": "爱好"}],
    "sho": [{"word": "しょうがつ", "romaji": "shougatsu", "kanji": "正月", "meaning": "新年"}],
    "cha": [{"word": "おちゃ", "romaji": "ocha", "kanji": "お茶", "meaning": "茶"}],
    "chu": [{"word": "ちゅうごく", "romaji": "chuugoku", "kanji": "中国", "meaning": "中国"}],
    "cho": [{"word": "ちょっと", "romaji": "chotto", "kanji": "", "meaning": "稍微"}],
    "nya": [{"word": "にゃん", "romaji": "nyan", "kanji": "", "meaning": "喵（猫叫声）"}],
    "nyu": [{"word": "にゅうがく", "romaji": "nyuugaku", "kanji": "入学", "meaning": "入学"}],
    "nyo": [{"word": "にょうぼう", "romaji": "nyoubou", "kanji": "女房", "meaning": "妻子"}],
    "hya": [{"word": "ひゃく", "romaji": "hyaku", "kanji": "百", "meaning": "一百"}],
    "hyu": [{"word": "ひゅうが", "romaji": "hyuuga", "kanji": "日向", "meaning": "向阳处"}],
    "hyo": [{"word": "ひょうばん", "romaji": "hyouban", "kanji": "評判", "meaning": "评价"}],
    "mya": [{"word": "みゃく", "romaji": "myaku", "kanji": "脈", "meaning": "脉搏"}],
    "myu": [{"word": "ミュージック", "romaji": "myuujikku", "kanji": "", "meaning": "音乐"}],
    "myo": [{"word": "みょうじ", "romaji": "myouji", "kanji": "名字", "meaning": "姓"}],
    "rya": [{"word": "りゃくご", "romaji": "ryakugo", "kanji": "略語", "meaning": "缩略语"}],
    "ryu": [{"word": "りゅうがく", "romaji": "ryuugaku", "kanji": "留学", "meaning": "留学"}],
    "ryo": [{"word": "りょこう", "romaji": "ryokou", "kanji": "旅行", "meaning": "旅行"},
            {"word": "りょうり", "romaji": "ryouri", "kanji": "料理", "meaning": "料理"}],
    "gya": [{"word": "ぎゃく", "romaji": "gyaku", "kanji": "逆", "meaning": "相反"}],
    "gyu": [{"word": "ぎゅうにく", "romaji": "gyuuniku", "kanji": "牛肉", "meaning": "牛肉"}],
    "gyo": [{"word": "ぎょうれつ", "romaji": "gyouretsu", "kanji": "行列", "meaning": "队列"}],
    "ja": [{"word": "じゃあね", "romaji": "jaane", "kanji": "", "meaning": "再见（口语）"}],
    "ju": [{"word": "じゅぎょう", "romaji": "jugyou", "kanji": "授業", "meaning": "课程"}],
    "jo": [{"word": "じょうず", "romaji": "jouzu", "kanji": "上手", "meaning": "擅长"}],
    "bya": [{"word": "びゃくや", "romaji": "byakuya", "kanji": "白夜", "meaning": "白夜"}],
    "byu": [{"word": "ビュー", "romaji": "byuu", "kanji": "", "meaning": "景色"}],
    "byo": [{"word": "びょうき", "romaji": "byouki", "kanji": "病気", "meaning": "生病"}],
    "pya": [{"word": "ろっぴゃく", "romaji": "roppyaku", "kanji": "六百", "meaning": "六百"}],
    "pyu": [{"word": "コンピューター", "romaji": "konpyuutaa", "kanji": "", "meaning": "电脑"}],
    "pyo": [{"word": "ぴょんぴょん", "romaji": "pyonpyon", "kanji": "", "meaning": "蹦蹦跳跳"}],
}

ROW_LABELS = {
    "a": "あ行", "ka": "か行", "sa": "さ行", "ta": "た行", "na": "な行",
    "ha": "は行", "ma": "ま行", "ya": "や行", "ra": "ら行", "wa": "わ行",
    "ga": "が行", "za": "ざ行", "da": "だ行", "ba": "ば行", "pa": "ぱ行",
    "kya": "きゃ行", "sha": "しゃ行", "cha": "ちゃ行", "nya": "にゃ行",
    "hya": "ひゃ行", "mya": "みゃ行", "rya": "りゃ行",
    "gya": "ぎゃ行", "ja": "じゃ行", "bya": "びゃ行", "pya": "ぴゃ行",
}

TYPE_LABELS = {
    "seion": "清音",
    "dakuon": "浊音",
    "handakuon": "半浊音",
    "youon": "拗音",
}
